<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.14" />
      <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.15.1" />
      <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.2" />
      <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.1" />
      <PackageReference Include="Serilog.Sinks.Grafana.Loki" Version="8.3.2" />
      <PackageReference Include="SonarAnalyzer.CSharp" Version="10.22.0.136894">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" Version="9.0.14" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.14" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.14" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.14" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
        <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="System.Net.Http" Version="4.3.4" />
        <PackageReference Include="System.Private.Uri" Version="4.3.2" />
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\TcpHealthProbe\TcpHealthProbe.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="appsettings.development.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
    
    <ItemGroup>
        <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
    </ItemGroup>

</Project>
